<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Bielu.AspNetCore.AsyncApi" />
    <PackageReference Include="Bielu.AspNetCore.AsyncApi.UI" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\bielu.tdsharp.asyncapi\bielu.tdsharp.asyncapi.csproj" />
  </ItemGroup>

</Project>
