<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Bielu.AspNetCore.AsyncApi.Attributes" />
    <PackageReference Include="TDLib" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\bielu.tdsharp.abstractions\bielu.tdsharp.abstractions.csproj" />
  </ItemGroup>

</Project>
